name: Pull Request AutoMerge

on: [push]

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        merge-method: 'merge' # Default 'squash'
        min-approvals: 1 # Default 2
        base-ref: 'dev' # Default 'dev'
        
